In [1]:
import torch
import pickle
import numpy as np
import pandas as pd
import os
import json 
from os.path import dirname



root_path = dirname(os.getcwd()) + "/SEPH_TIME"

pd.set_option("display.max_columns", None)
data_dir = root_path + "/data/datasets/original/"
data_dir_processed = root_path + "/data/datasets/processed/"
data_dir_graphs = root_path + "/data/datasets/graphs_repair/"

print(root_path, data_dir, data_dir_processed, data_dir_graphs, sep="\n")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
# device = "cpu"

/home/matteo/Documents/GNN-test2/SEPH_MODELS/SEPH_TIME
/home/matteo/Documents/GNN-test2/SEPH_MODELS/SEPH_TIME/data/datasets/original/
/home/matteo/Documents/GNN-test2/SEPH_MODELS/SEPH_TIME/data/datasets/processed/
/home/matteo/Documents/GNN-test2/SEPH_MODELS/SEPH_TIME/data/datasets/graphs_repair/

In [2]:
with open("data/dataset_features.json", 'r') as file:
    datasets_info = json.load(file)

In [3]:
list(datasets_info.keys())

['BPI12_DECLINED_COMPLETE',
 'sepsis_cases_1',
 'sepsis_cases_4',
 'BPIC15_common']

In [4]:
dataset = "sepsis_cases_1"

In [5]:
if dataset.startswith("BPIC15"):
    with open("data/dataset_features.json", 'r') as file:
        dataset_info = json.load(file)["BPIC15_common"]
else:
    with open("data/dataset_features.json", 'r') as file:
        dataset_info = json.load(file)[dataset]

In [6]:
categorical_columns = dataset_info["categorical"]
real_value_columns = dataset_info["numerical"]

In [7]:
tab_all = pd.read_csv(data_dir_processed+dataset+"_processed_all.csv")
tab_all.head()

,Diagnose,DiagnosticArtAstrup,DiagnosticBlood,DiagnosticECG,DiagnosticIC,DiagnosticLacticAcid,DiagnosticLiquor,DiagnosticOther,DiagnosticSputum,DiagnosticUrinaryCulture,DiagnosticUrinarySediment,DiagnosticXthorax,DisfuncOrg,Hypotensie,Hypoxie,InfectionSuspected,Infusion,Oligurie,SIRSCritHeartRate,SIRSCritLeucos,SIRSCritTachypnea,SIRSCritTemperature,SIRSCriteria2OrMore,Age,CaseID,Activity,org:group,CRP,LacticAcid,Leucocytes,time:timestamp,timesincemidnight,month,weekday,hour,timesincelastevent,timesincecasestart,event_nr,open_cases,label,remaining_time
0,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Registration,A,0.0,0.0,0.0,1.413955e+09,555,10,2,9,0.000000,0.000000,1,81,regular,968359.0
1,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,Leucocytes,B,0.0,0.0,9.6,1.413956e+09,567,10,2,9,0.000000,11.316667,2,81,regular,967680.0
2,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,CRP,B,21.0,0.0,9.6,1.413956e+09,567,10,2,9,0.000000,11.316667,3,81,regular,967680.0
3,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,LacticAcid,B,21.0,2.2,9.6,1.413956e+09,567,10,2,9,11.316667,11.316667,4,81,regular,967680.0
4,A,True,True,True,True,True,False,False,False,True,True,True,True,True,False,True,True,False,True,False,True,True,True,85.0,A,ER Triage,C,21.0,2.2,9.6,1.413956e+09,573,10,2,9,6.616667,17.933333,5,81,regular,967283.0

In [8]:
import pandas as pd

tab_test = pd.read_csv(data_dir_processed + f"{dataset}_processed_test.csv")

# time:timestamp should be in float representing number of seconds.
durations = (
    tab_test
    .groupby("CaseID")["time:timestamp"]
    .agg(start="min", end="max")
)
durations["duration_sec"] = (durations["end"] - durations["start"])

# 4) Compute averages
avg_sec  = durations["duration_sec"].mean()
avg_days = avg_sec / (24 * 3600)

print(f"Average trace duration (test set): {avg_sec:,.0f} seconds\n")
print(f"which means ≃ {avg_days:.1f} days")

Average trace duration (test set): 651,358 seconds

which means ≃ 7.5 days

In [9]:
import random

torch.manual_seed(0)
torch.cuda.manual_seed(0)
random.seed(0)
np.random.seed(0)

In [10]:
with open(data_dir_graphs + dataset + "_TRAIN_repair.pkl", "rb") as f:
    X_train = pickle.load(f)
with open(data_dir_graphs + dataset + "_VALID_repair.pkl", "rb") as f:
    X_valid = pickle.load(f)
with open(data_dir_graphs + dataset + "_TEST_repair.pkl", "rb") as f:
    X_test = pickle.load(f)

In [11]:

from torch_geometric.data import Dataset
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import ToUndirected, NormalizeFeatures, Compose

#transform = ToUndirected()
transform = Compose([ToUndirected(), NormalizeFeatures()])

with torch.no_grad():
        for i in range(len(X_train)):
                X_train[i] = transform(X_train[i])
        for i in range(len(X_valid)):
                X_valid[i] = transform(X_valid[i])
        for i in range(len(X_test)):
                X_test[i] = transform(X_test[i])

In [12]:
edge_types = set()
node_types = set()
for i in range(len(X_train)):
    n, edge_type = X_train[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)
for i in range(len(X_valid)):
    n, edge_type = X_valid[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)
for i in range(len(X_test)):
    n, edge_type = X_test[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)

In [13]:
node_types = list(node_types)
edge_types = list(edge_types)

In [14]:
node_types

['DiagnosticIC',
 'timesincecasestart',
 'DiagnosticArtAstrup',
 'timesincemidnight',
 'Hypotensie',
 'SIRSCritTemperature',
 'month',
 'DiagnosticLacticAcid',
 'Activity',
 'Hypoxie',
 'DiagnosticBlood',
 'SIRSCriteria2OrMore',
 'DiagnosticUrinarySediment',
 'Leucocytes',
 'DiagnosticXthorax',
 'CRP',
 'SIRSCritLeucos',
 'Infusion',
 'DiagnosticUrinaryCulture',
 'DiagnosticECG',
 'timesincelastevent',
 'Diagnose',
 'DiagnosticSputum',
 'Age',
 'SIRSCritHeartRate',
 'hour',
 'event_nr',
 'InfectionSuspected',
 'weekday',
 'org:group',
 'SIRSCritTachypnea',
 'DisfuncOrg',
 'DiagnosticLiquor',
 'Oligurie',
 'LacticAcid',
 'open_cases',
 'time:timestamp',
 'DiagnosticOther']

In [15]:
edge_types

[('Activity', 'related_to', 'Infusion'),
 ('InfectionSuspected', 'related_to', 'InfectionSuspected'),
 ('DiagnosticXthorax', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'DisfuncOrg'),
 ('Activity', 'related_to', 'SIRSCriteria2OrMore'),
 ('Activity', 'related_to', 'SIRSCritTemperature'),
 ('event_nr', 'rev_related_to', 'Activity'),
 ('Diagnose', 'related_to', 'Diagnose'),
 ('DiagnosticXthorax', 'related_to', 'DiagnosticXthorax'),
 ('Activity', 'related_to', 'Leucocytes'),
 ('Activity', 'related_to', 'time:timestamp'),
 ('Activity', 'related_to', 'DiagnosticUrinaryCulture'),
 ('Activity', 'related_to', 'Hypotensie'),
 ('hour', 'related_to', 'hour'),
 ('Activity', 'related_to', 'DiagnosticSputum'),
 ('DisfuncOrg', 'related_to', 'DisfuncOrg'),
 ('org:group', 'rev_related_to', 'Activity'),
 ('Hypotensie', 'rev_related_to', 'Activity'),
 ('Diagnose', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'DiagnosticLacticAcid'),
 ('Activity', 'related_to', 'CRP'),
 ('month', 'rev_related_to', 'Activity'),
 ('Oligurie', 'related_to', 'Oligurie'),
 ('timesincecasestart', 'rev_related_to', 'Activity'),
 ('open_cases', 'related_to', 'open_cases'),
 ('Activity', 'related_to', 'DiagnosticLiquor'),
 ('Activity', 'related_to', 'timesincelastevent'),
 ('timesincelastevent', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'InfectionSuspected'),
 ('Activity', 'related_to', 'event_nr'),
 ('Leucocytes', 'rev_related_to', 'Activity'),
 ('weekday', 'related_to', 'weekday'),
 ('SIRSCritTemperature', 'rev_related_to', 'Activity'),
 ('DiagnosticArtAstrup', 'related_to', 'DiagnosticArtAstrup'),
 ('SIRSCritTachypnea', 'related_to', 'SIRSCritTachypnea'),
 ('Activity', 'related_to', 'Hypoxie'),
 ('timesincecasestart', 'related_to', 'timesincecasestart'),
 ('DiagnosticLacticAcid', 'rev_related_to', 'Activity'),
 ('timesincemidnight', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'DiagnosticArtAstrup'),
 ('Activity', 'related_to', 'open_cases'),
 ('DiagnosticSputum', 'rev_related_to', 'Activity'),
 ('Hypoxie', 'rev_related_to', 'Activity'),
 ('Hypotensie', 'related_to', 'Hypotensie'),
 ('time:timestamp', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'timesincemidnight'),
 ('Activity', 'related_to', 'month'),
 ('DiagnosticUrinaryCulture', 'rev_related_to', 'Activity'),
 ('hour', 'rev_related_to', 'Activity'),
 ('DiagnosticSputum', 'related_to', 'DiagnosticSputum'),
 ('SIRSCritTachypnea', 'rev_related_to', 'Activity'),
 ('Oligurie', 'rev_related_to', 'Activity'),
 ('SIRSCritHeartRate', 'rev_related_to', 'Activity'),
 ('LacticAcid', 'related_to', 'LacticAcid'),
 ('Activity', 'related_to', 'Age'),
 ('event_nr', 'related_to', 'event_nr'),
 ('DiagnosticECG', 'related_to', 'DiagnosticECG'),
 ('DiagnosticUrinarySediment', 'related_to', 'DiagnosticUrinarySediment'),
 ('DiagnosticUrinaryCulture', 'related_to', 'DiagnosticUrinaryCulture'),
 ('Activity', 'related_to', 'DiagnosticXthorax'),
 ('Leucocytes', 'related_to', 'Leucocytes'),
 ('SIRSCritTemperature', 'related_to', 'SIRSCritTemperature'),
 ('DiagnosticUrinarySediment', 'rev_related_to', 'Activity'),
 ('CRP', 'rev_related_to', 'Activity'),
 ('Infusion', 'related_to', 'Infusion'),
 ('Activity', 'related_to', 'DiagnosticIC'),
 ('SIRSCritLeucos', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'timesincecasestart'),
 ('DiagnosticIC', 'rev_related_to', 'Activity'),
 ('Infusion', 'rev_related_to', 'Activity'),
 ('Age', 'related_to', 'Age'),
 ('weekday', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'hour'),
 ('SIRSCritLeucos', 'related_to', 'SIRSCritLeucos'),
 ('timesincelastevent', 'related_to', 'timesincelastevent'),
 ('DiagnosticLiquor', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'Oligurie'),
 ('Activity', 'related_to', 'DiagnosticECG'),
 ('DiagnosticLacticAcid', 'related_to', 'DiagnosticLacticAcid'),
 ('Hypoxie', 'related_to', 'Hypoxie'),
 ('time:timestamp', 'related_to', 'time:timestamp'),
 ('DiagnosticIC', 'related_to', 'DiagnosticIC'),
 ('DiagnosticArtAstrup', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'LacticAcid'),
 ('org:group', 'related_to', 'org:group'),
 ('CRP', 'related_to', 'CRP'),
 ('InfectionSuspected', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'DiagnosticUrinarySediment'),
 ('DiagnosticOther', 'rev_related_to', 'Activity'),
 ('DiagnosticBlood', 'related_to', 'DiagnosticBlood'),
 ('Activity', 'followed_by', 'Activity'),
 ('LacticAcid', 'rev_related_to', 'Activity'),
 ('timesincemidnight', 'related_to', 'timesincemidnight'),
 ('SIRSCriteria2OrMore', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'SIRSCritHeartRate'),
 ('SIRSCritHeartRate', 'related_to', 'SIRSCritHeartRate'),
 ('DiagnosticECG', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'SIRSCritLeucos'),
 ('SIRSCriteria2OrMore', 'related_to', 'SIRSCriteria2OrMore'),
 ('DiagnosticOther', 'related_to', 'DiagnosticOther'),
 ('Activity', 'related_to', 'DiagnosticOther'),
 ('Activity', 'related_to', 'SIRSCritTachypnea'),
 ('month', 'related_to', 'month'),
 ('open_cases', 'rev_related_to', 'Activity'),
 ('DiagnosticLiquor', 'related_to', 'DiagnosticLiquor'),
 ('DisfuncOrg', 'rev_related_to', 'Activity'),
 ('DiagnosticBlood', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'DiagnosticBlood'),
 ('Activity', 'related_to', 'Diagnose'),
 ('Activity', 'related_to', 'org:group'),
 ('Age', 'rev_related_to', 'Activity'),
 ('Activity', 'related_to', 'weekday')]

## Hyperopt

In [16]:
from ax.service.managed_loop import optimize

In [17]:
from torch_geometric.nn import (
    HeteroConv,
    global_mean_pool,
    GATv2Conv,
    SAGEConv,
    TransformerConv
)
from torch.nn import (
    ModuleList,
    Module,
    Linear
  )
from typing_extensions import Self

In [18]:
from torch.nn import Module, ModuleList, Linear
import torch.nn as nn
from torch_geometric.nn import HeteroConv, SAGEConv, global_mean_pool

class HGNN(Module):
    def __init__(self, node_types, edge_types, parameters):
        super().__init__()
        hid = parameters["hid"]
        layers = parameters["layers"]
        aggregation = parameters["aggregation"]
        
        self.node_types = node_types
        self.edge_types = edge_types
        
        # Convolutional layers for heterogeneous graph
        self.convs = ModuleList()
        for _ in range(layers):
            conv = HeteroConv(
                {relation: SAGEConv((-1, -1), hid, aggr=aggregation)
                 for relation in edge_types},
                aggr=aggregation
            )
            self.convs.append(conv)
        
        # Linear layer for graph-level prediction
        self.lin = Linear(len(node_types) * hid, 1)
    
    def forward(self, batch):
        x_dict = batch.x_dict
        edge_index_dict = batch.edge_index_dict
        
        # Apply convolutional layers
        for conv in self.convs:
            x_dict = conv(x_dict, edge_index_dict)
            x_dict = {key: x.relu() for key, x in x_dict.items()}
        
        # Pool node features for each node type
        graph_features = []
        for node_type in self.node_types:
            x = x_dict[node_type]
            batch_idx = batch[node_type].batch  # Batch index for pooling
            pooled = global_mean_pool(x, batch_idx)
            graph_features.append(pooled)
        
        # Concatenate pooled features
        graph_features = torch.cat(graph_features, dim=-1)
        
        # Predict remaining time
        output = self.lin(graph_features).squeeze(-1)
        return output  # Shape: [batch_size]

In [19]:
from torcheval.metrics.functional import multiclass_accuracy, multiclass_f1_score

In [20]:
import torch.nn as nn

In [21]:
import time

In [22]:
from torch_geometric.data import DataLoader
from copy import deepcopy

def train_hgnn(config, node_types, edge_types, epochs=50):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    net = HGNN(node_types=node_types, edge_types=edge_types, parameters=config).to(device)
    loss_fn = nn.L1Loss()  # MAE for regression
    optimizer = torch.optim.Adam(net.parameters(), lr=config["lr"])
    
    train_loader = DataLoader(X_train, batch_size=config["batch_size"], shuffle=True)
    valid_loader = DataLoader(X_valid, batch_size=config["batch_size"], shuffle=False)
    
    best_model = None
    best_loss = float("inf")
    patience = 5
    pat_count = 0
    
    for epoch in range(epochs):
        net.train()
        train_losses = []
        for batch in train_loader:
            batch = batch.to(device)
            optimizer.zero_grad()
            preds = net(batch)  # Graph-level predictions
            true = batch.y  # Graph-level targets
            loss = loss_fn(preds, true)
            loss.backward()
            optimizer.step()
            train_losses.append(loss.item())
        
        avg_train_loss = sum(train_losses) / len(train_losses)
        
        net.eval()
        valid_losses = []
        with torch.no_grad():
            for batch in valid_loader:
                batch = batch.to(device)
                preds = net(batch)
                true = batch.y
                valid_losses.append(loss_fn(preds, true).item())
        
        avg_val_loss = sum(valid_losses) / len(valid_losses)
        
        print(f"Epoch {epoch+1}/{epochs}, Train MAE: {avg_train_loss:.4f}, Valid MAE: {avg_val_loss:.4f}")
        
        if avg_val_loss < best_loss:
            best_loss = avg_val_loss
            best_model = deepcopy(net)
            pat_count = 0
        else:
            pat_count += 1
            if pat_count >= patience:
                print("Early stopping")
                break
    
    return best_model

In [23]:
def test_hgnn(net):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_loader = DataLoader(X_test, batch_size=128, shuffle=False)
    all_preds = []
    all_targets = []
    net.eval()
    with torch.no_grad():
        for batch in test_loader:
            batch = batch.to(device)
            preds = net(batch)
            all_preds.append(preds)
            all_targets.append(batch.y)
    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    mae = nn.L1Loss()(all_preds, all_targets).item()
    print(f"Test MAE: {mae:.4f}")
    return {"remaining_time_mae": mae}

In [24]:
outputreal = ["remaining_time"]
print(outputreal)

['remaining_time']

In [25]:
def train_evaluate(config):
    trained_net = train_hgnn(config, node_types=node_types,edge_types=edge_types, epochs=50)
    return test_hgnn(trained_net)

In [26]:
import logging

logging.getLogger("root").setLevel(logging.ERROR)

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [27]:
sample_config = {
    "hid":          128, #128
    "layers":       2, #2
    "lr":           1e-3,
    "batch_size":   256, #256
    "aggregation": "mean",
}

# 1-epoch train just to exercise the code-path and see prints
net = train_hgnn(sample_config,node_types=node_types,edge_types=edge_type, epochs=1)

# run the test (with your debug prints enabled)
res = test_hgnn(net)
print("test_hgnn returned:", res)

Epoch 1/1, Train MAE: 670347.8750, Valid MAE: 713625.8750
Test MAE: 649003.3125
test_hgnn returned: {'remaining_time_mae': 649003.3125}

In [28]:
best_parameters, values, experiment, model = optimize(
    parameters=[
        {"name": "hid", "type": "choice", "values": [128], "value_type": "int", "is_ordered" : True,"sort_values":False},
        #{"name": "layers", "type": "choice", "values": [2, 3, 4, 5], "value_type": "int", "is_ordered" : True, "sort_values":False},
        {"name": "layers", "type": "choice", "values": [2], "value_type": "int", "is_ordered" : True, "sort_values":False},
        {"name": "lr", "type": "range", "bounds": [1e-4, 1e-1], "value_type": "float", "log_scale": True},
        {"name": "batch_size", "type": "choice", "values": [128,256,512], "value_type": "int", "is_ordered" : True,"sort_values":False}, 
        
        #{"name": "heads", "type": "choice", "values": [1,2], "value_type": "int", "is_ordered" : True,"sort_values":False},
        #{"name": "heads", "type": "choice", "values": [1], "value_type": "int", "is_ordered" : True,"sort_values":False},
        
        {"name": "aggregation", "type" : "choice", "values" :["sum", "mean", "max"], "value_type" : "str"}
        #{"name": "aggregation", "type" : "choice", "values" :["max"], "value_type" : "str"},
     
    ],
  
    evaluation_function=lambda config:train_evaluate({**config,"nodes_relations": edge_types}),
    objective_name='remaining_time_mae',
    arms_per_trial=1,
    minimize = True,
    random_seed = 123,
    total_trials = 15
)

print("Best parameters:", best_parameters)
means, covariances = values
print("Means", means)
print("Experiment:", experiment)

[INFO 06-19 19:38:53] ax.service.utils.instantiation: Choice parameter hid contains only one value, converting to a fixed parameter instead.
[INFO 06-19 19:38:53] ax.service.utils.instantiation: Choice parameter layers contains only one value, converting to a fixed parameter instead.
/home/matteo/Documents/GNN-test2/SEPH_MODELS/env3/lib/python3.10/site-packages/ax/service/utils/instantiation.py:248: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "aggregation". Defaulting to `False`  since the parameter is a string with more than 2 choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
/home/matteo/Documents/GNN-test2/SEPH_MODELS/env3/lib/python3.10/site-packages/ax/service/utils/instantiation.py:248: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "aggregation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 06-19 19:38:53] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[FixedParameter(name='hid', parameter_type=INT, value=128), FixedParameter(name='layers', parameter_type=INT, value=2), RangeParameter(name='lr', parameter_type=FLOAT, range=[0.0001, 0.1], log_scale=True), ChoiceParameter(name='batch_size', parameter_type=INT, values=[128, 256, 512], is_ordered=True, sort_values=False), ChoiceParameter(name='aggregation', parameter_type=STRING, values=['sum', 'mean', 'max'], is_ordered=False, sort_values=False)], parameter_constraints=[]).
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: Using Bayesian optimization with a categorical kernel for improved performance with a large number of unordered categorical parameters.
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=3 num_trials=None use_batch_trials=False
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=6
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=6
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 06-19 19:38:53] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BO_MIXED', steps=[Sobol for 6 trials, BO_MIXED for subsequent trials]). Iterations after 6 will take longer to generate due to model-fitting.
[INFO 06-19 19:38:53] ax.service.managed_loop: Started full optimization with 15 steps.
[INFO 06-19 19:38:53] ax.service.managed_loop: Running optimization trial 1...

Epoch 1/50, Train MAE: 649527.3438, Valid MAE: 713627.1875
Epoch 2/50, Train MAE: 663657.5938, Valid MAE: 713626.8125
Epoch 3/50, Train MAE: 672171.8438, Valid MAE: 713626.5000
Epoch 4/50, Train MAE: 649544.0625, Valid MAE: 713626.1875
Epoch 5/50, Train MAE: 654446.3750, Valid MAE: 713625.8750
Epoch 6/50, Train MAE: 654881.6875, Valid MAE: 713625.5000
Epoch 7/50, Train MAE: 673858.1875, Valid MAE: 713625.1250
Epoch 8/50, Train MAE: 659671.2812, Valid MAE: 713624.7500
Epoch 9/50, Train MAE: 666171.7500, Valid MAE: 713624.3750
Epoch 10/50, Train MAE: 655997.7812, Valid MAE: 713623.9375
Epoch 11/50, Train MAE: 675508.6875, Valid MAE: 713623.4375
Epoch 12/50, Train MAE: 660783.3750, Valid MAE: 713623.0000
Epoch 13/50, Train MAE: 658108.1562, Valid MAE: 713622.3750
Epoch 14/50, Train MAE: 665521.3125, Valid MAE: 713621.8750
Epoch 15/50, Train MAE: 667973.2812, Valid MAE: 713621.2500
Epoch 16/50, Train MAE: 654138.5000, Valid MAE: 713620.5625
Epoch 17/50, Train MAE: 670232.8125, Valid MAE: 713619.8750
Epoch 18/50, Train MAE: 665404.0938, Valid MAE: 713619.1250
Epoch 19/50, Train MAE: 663445.4062, Valid MAE: 713618.3125
Epoch 20/50, Train MAE: 667687.1875, Valid MAE: 713617.4375
Epoch 21/50, Train MAE: 667145.6562, Valid MAE: 713616.5625
Epoch 22/50, Train MAE: 653008.0625, Valid MAE: 713615.4375
Epoch 23/50, Train MAE: 664413.2500, Valid MAE: 713614.5000
Epoch 24/50, Train MAE: 659788.3750, Valid MAE: 713613.3125
Epoch 25/50, Train MAE: 654619.8125, Valid MAE: 713612.1875
Epoch 26/50, Train MAE: 668681.1562, Valid MAE: 713610.8750
Epoch 27/50, Train MAE: 650953.0000, Valid MAE: 713609.6250
Epoch 28/50, Train MAE: 677370.6250, Valid MAE: 713608.2500
Epoch 29/50, Train MAE: 642679.4062, Valid MAE: 713606.6250
Epoch 30/50, Train MAE: 667207.8438, Valid MAE: 713605.1250
Epoch 31/50, Train MAE: 676207.8438, Valid MAE: 713603.5000
Epoch 32/50, Train MAE: 652990.9375, Valid MAE: 713601.7500
Epoch 33/50, Train MAE: 670818.9062, Valid MAE: 713599.9375
Epoch 34/50, Train MAE: 657406.0938, Valid MAE: 713598.0000
Epoch 35/50, Train MAE: 655222.9375, Valid MAE: 713595.9375
Epoch 36/50, Train MAE: 663852.6250, Valid MAE: 713593.8750
Epoch 37/50, Train MAE: 656739.3438, Valid MAE: 713591.6250
Epoch 38/50, Train MAE: 663062.5625, Valid MAE: 713589.3125
Epoch 39/50, Train MAE: 668859.0625, Valid MAE: 713586.8750
Epoch 40/50, Train MAE: 666127.4375, Valid MAE: 713584.3750
Epoch 41/50, Train MAE: 668750.7500, Valid MAE: 713581.6875
Epoch 42/50, Train MAE: 664421.4375, Valid MAE: 713578.8750
Epoch 43/50, Train MAE: 676992.5000, Valid MAE: 713576.0625
Epoch 44/50, Train MAE: 659684.9375, Valid MAE: 713573.0000
Epoch 45/50, Train MAE: 668596.1562, Valid MAE: 713569.8125
Epoch 46/50, Train MAE: 674064.6250, Valid MAE: 713566.5625
Epoch 47/50, Train MAE: 657884.0625, Valid MAE: 713563.1875
Epoch 48/50, Train MAE: 657378.0000, Valid MAE: 713559.5625
Epoch 49/50, Train MAE: 660711.0938, Valid MAE: 713555.8750
Epoch 50/50, Train MAE: 666513.0938, Valid MAE: 713552.0625

[INFO 06-19 19:41:00] ax.service.managed_loop: Running optimization trial 2...

Test MAE: 648929.6250
Epoch 1/50, Train MAE: 638850.0625, Valid MAE: 598845.8125
Epoch 2/50, Train MAE: 484338.8359, Valid MAE: 488593.2500
Epoch 3/50, Train MAE: 413217.4297, Valid MAE: 412528.4688
Epoch 4/50, Train MAE: 383293.1953, Valid MAE: 437735.6875
Epoch 5/50, Train MAE: 403725.0156, Valid MAE: 396761.2500
Epoch 6/50, Train MAE: 353709.2578, Valid MAE: 392624.3438
Epoch 7/50, Train MAE: 338673.8438, Valid MAE: 404900.3125
Epoch 8/50, Train MAE: 334018.6953, Valid MAE: 390219.5938
Epoch 9/50, Train MAE: 356459.3438, Valid MAE: 388733.4375
Epoch 10/50, Train MAE: 338285.8672, Valid MAE: 386350.6250
Epoch 11/50, Train MAE: 346513.7109, Valid MAE: 386494.6250
Epoch 12/50, Train MAE: 377061.7266, Valid MAE: 385192.6250
Epoch 13/50, Train MAE: 310647.7539, Valid MAE: 383149.2188
Epoch 14/50, Train MAE: 313928.8594, Valid MAE: 382651.5000
Epoch 15/50, Train MAE: 347682.9375, Valid MAE: 384432.8125
Epoch 16/50, Train MAE: 305416.2812, Valid MAE: 389632.8438
Epoch 17/50, Train MAE: 289512.2148, Valid MAE: 393371.7188
Epoch 18/50, Train MAE: 299327.1016, Valid MAE: 395099.8438
Epoch 19/50, Train MAE: 337862.7266, Valid MAE: 396883.1250
Early stopping

[INFO 06-19 19:41:54] ax.service.managed_loop: Running optimization trial 3...

Test MAE: 330127.9062
Epoch 1/50, Train MAE: 663310.2500, Valid MAE: 713624.3750
Epoch 2/50, Train MAE: 663307.2500, Valid MAE: 713620.4375
Epoch 3/50, Train MAE: 663303.2500, Valid MAE: 713614.8750
Epoch 4/50, Train MAE: 663297.6875, Valid MAE: 713607.3125
Epoch 5/50, Train MAE: 663290.2500, Valid MAE: 713597.5625
Epoch 6/50, Train MAE: 663280.4375, Valid MAE: 713585.3750
Epoch 7/50, Train MAE: 663268.2500, Valid MAE: 713570.3125
Epoch 8/50, Train MAE: 663253.2500, Valid MAE: 713552.0000
Epoch 9/50, Train MAE: 663234.9375, Valid MAE: 713530.3125
Epoch 10/50, Train MAE: 663213.2500, Valid MAE: 713504.5625
Epoch 11/50, Train MAE: 663187.5625, Valid MAE: 713474.3750
Epoch 12/50, Train MAE: 663157.4375, Valid MAE: 713439.3750
Epoch 13/50, Train MAE: 663122.4375, Valid MAE: 713398.9375
Epoch 14/50, Train MAE: 663082.0625, Valid MAE: 713352.5625
Epoch 15/50, Train MAE: 663035.6875, Valid MAE: 713299.5625
Epoch 16/50, Train MAE: 662982.7500, Valid MAE: 713239.3750
Epoch 17/50, Train MAE: 662922.5625, Valid MAE: 713171.1250
Epoch 18/50, Train MAE: 662854.4375, Valid MAE: 713094.3125
Epoch 19/50, Train MAE: 662777.6250, Valid MAE: 713008.0000
Epoch 20/50, Train MAE: 662691.3125, Valid MAE: 712911.3750
Epoch 21/50, Train MAE: 662594.6875, Valid MAE: 712803.5625
Epoch 22/50, Train MAE: 662486.9375, Valid MAE: 712683.5625
Epoch 23/50, Train MAE: 662366.9375, Valid MAE: 712550.5625
Epoch 24/50, Train MAE: 662233.9375, Valid MAE: 712403.2500
Epoch 25/50, Train MAE: 662086.6250, Valid MAE: 712240.8125
Epoch 26/50, Train MAE: 661924.0625, Valid MAE: 712061.8125
Epoch 27/50, Train MAE: 661745.1250, Valid MAE: 711865.2500
Epoch 28/50, Train MAE: 661548.4375, Valid MAE: 711649.6875
Epoch 29/50, Train MAE: 661332.8750, Valid MAE: 711414.0000
Epoch 30/50, Train MAE: 661097.0000, Valid MAE: 711156.6250
Epoch 31/50, Train MAE: 660839.6250, Valid MAE: 710876.2500
Epoch 32/50, Train MAE: 660559.0625, Valid MAE: 710571.2500
Epoch 33/50, Train MAE: 660253.9375, Valid MAE: 710240.1250
Epoch 34/50, Train MAE: 659922.6875, Valid MAE: 709881.2500
Epoch 35/50, Train MAE: 659563.5625, Valid MAE: 709492.8125
Epoch 36/50, Train MAE: 659174.9375, Valid MAE: 709073.1250
Epoch 37/50, Train MAE: 658755.0000, Valid MAE: 708620.5625
Epoch 38/50, Train MAE: 658302.0625, Valid MAE: 708132.9375
Epoch 39/50, Train MAE: 657814.2500, Valid MAE: 707608.5625
Epoch 40/50, Train MAE: 657289.5625, Valid MAE: 707045.3125
Epoch 41/50, Train MAE: 656726.0000, Valid MAE: 706441.4375
Epoch 42/50, Train MAE: 656121.6250, Valid MAE: 705794.5000
Epoch 43/50, Train MAE: 655474.2500, Valid MAE: 705102.5625
Epoch 44/50, Train MAE: 654781.8750, Valid MAE: 704363.1875
Epoch 45/50, Train MAE: 654043.5625, Valid MAE: 703574.6250
Epoch 46/50, Train MAE: 653258.1250, Valid MAE: 702734.3125
Epoch 47/50, Train MAE: 652421.1250, Valid MAE: 701839.8750
Epoch 48/50, Train MAE: 651534.0000, Valid MAE: 700889.1250
Epoch 49/50, Train MAE: 650591.6875, Valid MAE: 699879.6875
Epoch 50/50, Train MAE: 649591.2500, Valid MAE: 698808.9375

[INFO 06-19 19:43:56] ax.service.managed_loop: Running optimization trial 4...

Test MAE: 634240.5000
Epoch 1/50, Train MAE: 653596.8438, Valid MAE: 713618.1875
Epoch 2/50, Train MAE: 666372.5312, Valid MAE: 713608.3750
Epoch 3/50, Train MAE: 673893.4062, Valid MAE: 713597.5625
Epoch 4/50, Train MAE: 652575.8438, Valid MAE: 713585.1250
Epoch 5/50, Train MAE: 660221.6875, Valid MAE: 713570.7500
Epoch 6/50, Train MAE: 656377.3438, Valid MAE: 713553.8125
Epoch 7/50, Train MAE: 673939.6875, Valid MAE: 713534.1875
Epoch 8/50, Train MAE: 663817.5938, Valid MAE: 713511.6250
Epoch 9/50, Train MAE: 671388.3750, Valid MAE: 713485.6875
Epoch 10/50, Train MAE: 666647.0000, Valid MAE: 713456.3125
Epoch 11/50, Train MAE: 669059.7500, Valid MAE: 713423.1875
Epoch 12/50, Train MAE: 665653.8750, Valid MAE: 713386.0000
Epoch 13/50, Train MAE: 659371.3750, Valid MAE: 713344.5625
Epoch 14/50, Train MAE: 666330.2500, Valid MAE: 713298.6875
Epoch 15/50, Train MAE: 657933.3750, Valid MAE: 713247.8750
Epoch 16/50, Train MAE: 658700.3125, Valid MAE: 713192.0000
Epoch 17/50, Train MAE: 657855.7500, Valid MAE: 713130.7500
Epoch 18/50, Train MAE: 658654.1250, Valid MAE: 713063.8750
Epoch 19/50, Train MAE: 669276.1562, Valid MAE: 712990.9375
Epoch 20/50, Train MAE: 658986.5000, Valid MAE: 712911.7500
Epoch 21/50, Train MAE: 657717.8125, Valid MAE: 712826.1250
Epoch 22/50, Train MAE: 653431.0938, Valid MAE: 712733.6875
Epoch 23/50, Train MAE: 667167.2188, Valid MAE: 712634.0625
Epoch 24/50, Train MAE: 670535.7500, Valid MAE: 712527.0000
Epoch 25/50, Train MAE: 674029.8750, Valid MAE: 712412.2500
Epoch 26/50, Train MAE: 664055.6875, Valid MAE: 712289.3750
Epoch 27/50, Train MAE: 661671.1562, Valid MAE: 712158.1875
Epoch 28/50, Train MAE: 664667.0312, Valid MAE: 712018.3750
Epoch 29/50, Train MAE: 665421.7812, Valid MAE: 711869.5000
Epoch 30/50, Train MAE: 668973.5938, Valid MAE: 711711.3125
Epoch 31/50, Train MAE: 653509.6875, Valid MAE: 711543.4375
Epoch 32/50, Train MAE: 651764.0938, Valid MAE: 711365.6875
Epoch 33/50, Train MAE: 660655.4062, Valid MAE: 711177.6875
Epoch 34/50, Train MAE: 654156.2812, Valid MAE: 710979.0625
Epoch 35/50, Train MAE: 659347.8125, Valid MAE: 710769.4375
Epoch 36/50, Train MAE: 668880.9375, Valid MAE: 710548.5000
Epoch 37/50, Train MAE: 663622.7188, Valid MAE: 710315.9375
Epoch 38/50, Train MAE: 656545.7812, Valid MAE: 710071.5625
Epoch 39/50, Train MAE: 664308.2500, Valid MAE: 709814.6875
Epoch 40/50, Train MAE: 672731.9688, Valid MAE: 709545.3125
Epoch 41/50, Train MAE: 670220.0625, Valid MAE: 709262.8750
Epoch 42/50, Train MAE: 648081.2188, Valid MAE: 708967.1875
Epoch 43/50, Train MAE: 646029.7500, Valid MAE: 708657.6875
Epoch 44/50, Train MAE: 646802.3125, Valid MAE: 708334.1250
Epoch 45/50, Train MAE: 653288.1562, Valid MAE: 707996.1875
Epoch 46/50, Train MAE: 674899.2500, Valid MAE: 707643.5000
Epoch 47/50, Train MAE: 663057.5312, Valid MAE: 707275.7500
Epoch 48/50, Train MAE: 640515.6250, Valid MAE: 706892.4375
Epoch 49/50, Train MAE: 644323.1250, Valid MAE: 706493.1875
Epoch 50/50, Train MAE: 650178.3750, Valid MAE: 706077.8125

[INFO 06-19 19:46:21] ax.service.managed_loop: Running optimization trial 5...

Test MAE: 641460.8125
Epoch 1/50, Train MAE: 663312.0000, Valid MAE: 713590.2500
Epoch 2/50, Train MAE: 663273.2500, Valid MAE: 713539.4375
Epoch 3/50, Train MAE: 663222.5625, Valid MAE: 713465.3125
Epoch 4/50, Train MAE: 663148.6250, Valid MAE: 713361.7500
Epoch 5/50, Train MAE: 663045.1250, Valid MAE: 713222.8750
Epoch 6/50, Train MAE: 662906.4375, Valid MAE: 713042.3125
Epoch 7/50, Train MAE: 662726.0000, Valid MAE: 712812.6250
Epoch 8/50, Train MAE: 662496.6250, Valid MAE: 712526.1250
Epoch 9/50, Train MAE: 662210.1250, Valid MAE: 712173.5625
Epoch 10/50, Train MAE: 661857.4375, Valid MAE: 711745.0000
Epoch 11/50, Train MAE: 661428.7500, Valid MAE: 711229.5000
Epoch 12/50, Train MAE: 660913.1250, Valid MAE: 710614.9375
Epoch 13/50, Train MAE: 660298.4375, Valid MAE: 709888.3125
Epoch 14/50, Train MAE: 659571.6250, Valid MAE: 709035.2500
Epoch 15/50, Train MAE: 658718.3750, Valid MAE: 708040.8125
Epoch 16/50, Train MAE: 657723.6250, Valid MAE: 706888.2500
Epoch 17/50, Train MAE: 656570.4375, Valid MAE: 705559.6250
Epoch 18/50, Train MAE: 655240.9375, Valid MAE: 704035.8125
Epoch 19/50, Train MAE: 653718.8750, Valid MAE: 702296.7500
Epoch 20/50, Train MAE: 651990.2500, Valid MAE: 700321.4375
Epoch 21/50, Train MAE: 650032.8750, Valid MAE: 698087.3750
Epoch 22/50, Train MAE: 647819.3750, Valid MAE: 695571.3750
Epoch 23/50, Train MAE: 645326.2500, Valid MAE: 692748.5000
Epoch 24/50, Train MAE: 642529.3125, Valid MAE: 689592.9375
Epoch 25/50, Train MAE: 639402.6250, Valid MAE: 686077.1875
Epoch 26/50, Train MAE: 635922.1250, Valid MAE: 682172.5625
Epoch 27/50, Train MAE: 632087.7500, Valid MAE: 677848.3750
Epoch 28/50, Train MAE: 627844.6250, Valid MAE: 673073.1250
Epoch 29/50, Train MAE: 623159.2500, Valid MAE: 667814.9375
Epoch 30/50, Train MAE: 618000.1250, Valid MAE: 662040.7500
Epoch 31/50, Train MAE: 612357.8750, Valid MAE: 655715.5625
Epoch 32/50, Train MAE: 606202.8750, Valid MAE: 648804.2500
Epoch 33/50, Train MAE: 599521.4375, Valid MAE: 641269.0000
Epoch 34/50, Train MAE: 592242.6875, Valid MAE: 633133.1250
Epoch 35/50, Train MAE: 584390.5625, Valid MAE: 624405.5000
Epoch 36/50, Train MAE: 575967.2500, Valid MAE: 615116.7500
Epoch 37/50, Train MAE: 566923.6875, Valid MAE: 605246.2500
Epoch 38/50, Train MAE: 557301.3750, Valid MAE: 594650.8750
Epoch 39/50, Train MAE: 546922.1875, Valid MAE: 583236.9375
Epoch 40/50, Train MAE: 535863.6250, Valid MAE: 571108.2500
Epoch 41/50, Train MAE: 524225.5312, Valid MAE: 558447.0625
Epoch 42/50, Train MAE: 511885.7812, Valid MAE: 544926.2500
Epoch 43/50, Train MAE: 499029.6875, Valid MAE: 530473.2500
Epoch 44/50, Train MAE: 485427.1875, Valid MAE: 515056.8750
Epoch 45/50, Train MAE: 471138.3125, Valid MAE: 499262.4062
Epoch 46/50, Train MAE: 456272.0000, Valid MAE: 483306.9688
Epoch 47/50, Train MAE: 441170.5625, Valid MAE: 468002.5938
Epoch 48/50, Train MAE: 426315.4375, Valid MAE: 454131.7188
Epoch 49/50, Train MAE: 412122.7188, Valid MAE: 442585.5625
Epoch 50/50, Train MAE: 398017.3438, Valid MAE: 432899.1562

[INFO 06-19 19:48:28] ax.service.managed_loop: Running optimization trial 6...

Test MAE: 370438.8125
Epoch 1/50, Train MAE: 642617.0938, Valid MAE: 713403.2500
Epoch 2/50, Train MAE: 655429.0312, Valid MAE: 712381.0000
Epoch 3/50, Train MAE: 667430.4062, Valid MAE: 709663.3125
Epoch 4/50, Train MAE: 649726.5625, Valid MAE: 703908.1875
Epoch 5/50, Train MAE: 663008.0938, Valid MAE: 693228.1250
Epoch 6/50, Train MAE: 635212.1875, Valid MAE: 675135.5625
Epoch 7/50, Train MAE: 634744.4531, Valid MAE: 646494.2500
Epoch 8/50, Train MAE: 594178.2500, Valid MAE: 604576.7500
Epoch 9/50, Train MAE: 523466.4297, Valid MAE: 547396.3125
Epoch 10/50, Train MAE: 480965.0703, Valid MAE: 474119.0625
Epoch 11/50, Train MAE: 377488.0703, Valid MAE: 422145.1562
Epoch 12/50, Train MAE: 348566.9062, Valid MAE: 401279.0938
Epoch 13/50, Train MAE: 348609.7812, Valid MAE: 401464.5000
Epoch 14/50, Train MAE: 366405.9297, Valid MAE: 404235.5938
Epoch 15/50, Train MAE: 355264.0547, Valid MAE: 399862.9688
Epoch 16/50, Train MAE: 339020.2109, Valid MAE: 398186.8125
Epoch 17/50, Train MAE: 358449.6641, Valid MAE: 403022.3750
Epoch 18/50, Train MAE: 340863.7109, Valid MAE: 408090.0938
Epoch 19/50, Train MAE: 352015.0625, Valid MAE: 409351.5312
Epoch 20/50, Train MAE: 373372.4141, Valid MAE: 406863.5312
Epoch 21/50, Train MAE: 354451.5234, Valid MAE: 402764.8125
Early stopping

[INFO 06-19 19:49:35] ax.service.managed_loop: Running optimization trial 7...

Test MAE: 338728.7188
Epoch 1/50, Train MAE: 632774.1797, Valid MAE: 712778.3750
Epoch 2/50, Train MAE: 643614.2812, Valid MAE: 709342.6875
Epoch 3/50, Train MAE: 659421.0312, Valid MAE: 700530.8750
Epoch 4/50, Train MAE: 626270.3438, Valid MAE: 682172.8750
Epoch 5/50, Train MAE: 614346.6406, Valid MAE: 648575.3750
Epoch 6/50, Train MAE: 569500.9141, Valid MAE: 594002.8125
Epoch 7/50, Train MAE: 490937.1953, Valid MAE: 513421.0938
Epoch 8/50, Train MAE: 429971.4531, Valid MAE: 430726.5625
Epoch 9/50, Train MAE: 360669.2734, Valid MAE: 399368.3750
Epoch 10/50, Train MAE: 355113.9766, Valid MAE: 411798.4375
Epoch 11/50, Train MAE: 395479.2188, Valid MAE: 411531.1562
Epoch 12/50, Train MAE: 432227.6641, Valid MAE: 398147.6875
Epoch 13/50, Train MAE: 365238.0703, Valid MAE: 401257.0625
Epoch 14/50, Train MAE: 344940.3125, Valid MAE: 409227.6562
Epoch 15/50, Train MAE: 351373.9062, Valid MAE: 411567.7188
Epoch 16/50, Train MAE: 363680.3516, Valid MAE: 405342.7188
Epoch 17/50, Train MAE: 342922.9688, Valid MAE: 398746.4688
Early stopping

[INFO 06-19 19:50:30] ax.service.managed_loop: Running optimization trial 8...

Test MAE: 344461.9062
Epoch 1/50, Train MAE: 604062.1875, Valid MAE: 619184.0000
Epoch 2/50, Train MAE: 436934.3555, Valid MAE: 428840.6250
Epoch 3/50, Train MAE: 409189.4844, Valid MAE: 396374.4062
Epoch 4/50, Train MAE: 433830.2578, Valid MAE: 430161.5938
Epoch 5/50, Train MAE: 380964.3828, Valid MAE: 393410.5000
Epoch 6/50, Train MAE: 351688.4375, Valid MAE: 392098.9688
Epoch 7/50, Train MAE: 337154.2344, Valid MAE: 402887.4688
Epoch 8/50, Train MAE: 355226.1797, Valid MAE: 389844.5000
Epoch 9/50, Train MAE: 329425.5859, Valid MAE: 384946.7500
Epoch 10/50, Train MAE: 323577.8672, Valid MAE: 383671.5312
Epoch 11/50, Train MAE: 297058.5586, Valid MAE: 384829.8438
Epoch 12/50, Train MAE: 321300.2500, Valid MAE: 392031.0938
Epoch 13/50, Train MAE: 285922.5859, Valid MAE: 400258.0625
Epoch 14/50, Train MAE: 302350.7812, Valid MAE: 405614.7812
Epoch 15/50, Train MAE: 298214.7539, Valid MAE: 402854.9375
Early stopping

[INFO 06-19 19:51:28] ax.service.managed_loop: Running optimization trial 9...

Test MAE: 328314.2812
Epoch 1/50, Train MAE: 642726.9531, Valid MAE: 684440.0000
Epoch 2/50, Train MAE: 578966.0938, Valid MAE: 472425.4375
Epoch 3/50, Train MAE: 452671.0000, Valid MAE: 464363.4688
Epoch 4/50, Train MAE: 414585.0703, Valid MAE: 396115.8125
Epoch 5/50, Train MAE: 363762.9688, Valid MAE: 447566.2500
Epoch 6/50, Train MAE: 380825.1875, Valid MAE: 409433.1875
Epoch 7/50, Train MAE: 358614.4141, Valid MAE: 396008.4688
Epoch 8/50, Train MAE: 350739.1172, Valid MAE: 389469.2812
Epoch 9/50, Train MAE: 394665.1016, Valid MAE: 407290.9375
Epoch 10/50, Train MAE: 360502.1250, Valid MAE: 394687.8438
Epoch 11/50, Train MAE: 323029.8906, Valid MAE: 385017.7500
Epoch 12/50, Train MAE: 347747.0156, Valid MAE: 382542.2500
Epoch 13/50, Train MAE: 332433.6094, Valid MAE: 383165.5000
Epoch 14/50, Train MAE: 301032.8633, Valid MAE: 386996.2812
Epoch 15/50, Train MAE: 304208.4453, Valid MAE: 391416.1250
Epoch 16/50, Train MAE: 306552.5195, Valid MAE: 402309.2188
Epoch 17/50, Train MAE: 351773.0859, Valid MAE: 404014.4375
Early stopping

[INFO 06-19 19:52:24] ax.service.managed_loop: Running optimization trial 10...

Test MAE: 330205.0000
Epoch 1/50, Train MAE: 658021.2031, Valid MAE: 713625.0625
Epoch 2/50, Train MAE: 655174.0000, Valid MAE: 713622.5625
Epoch 3/50, Train MAE: 648984.5625, Valid MAE: 713620.1250
Epoch 4/50, Train MAE: 658349.7344, Valid MAE: 713617.5000
Epoch 5/50, Train MAE: 727570.3750, Valid MAE: 713614.8750
Epoch 6/50, Train MAE: 665439.9688, Valid MAE: 713612.1250
Epoch 7/50, Train MAE: 645407.4375, Valid MAE: 713609.2500
Epoch 8/50, Train MAE: 638830.8438, Valid MAE: 713606.1875
Epoch 9/50, Train MAE: 667613.5312, Valid MAE: 713602.8750
Epoch 10/50, Train MAE: 649875.3906, Valid MAE: 713599.3750
Epoch 11/50, Train MAE: 645767.7812, Valid MAE: 713595.7500
Epoch 12/50, Train MAE: 675386.9844, Valid MAE: 713591.6875
Epoch 13/50, Train MAE: 678081.0938, Valid MAE: 713587.5000
Epoch 14/50, Train MAE: 701164.2656, Valid MAE: 713582.8750
Epoch 15/50, Train MAE: 666668.5156, Valid MAE: 713578.0625
Epoch 16/50, Train MAE: 680585.9844, Valid MAE: 713572.8750
Epoch 17/50, Train MAE: 632028.5234, Valid MAE: 713567.2500
Epoch 18/50, Train MAE: 641552.5000, Valid MAE: 713561.4375
Epoch 19/50, Train MAE: 636459.6172, Valid MAE: 713555.1250
Epoch 20/50, Train MAE: 677800.1094, Valid MAE: 713548.5000
Epoch 21/50, Train MAE: 644981.5000, Valid MAE: 713541.5000
Epoch 22/50, Train MAE: 637364.2969, Valid MAE: 713534.0000
Epoch 23/50, Train MAE: 693128.2031, Valid MAE: 713526.3125
Epoch 24/50, Train MAE: 651017.7344, Valid MAE: 713518.0000
Epoch 25/50, Train MAE: 674865.6875, Valid MAE: 713509.4375
Epoch 26/50, Train MAE: 670036.9531, Valid MAE: 713500.3125
Epoch 27/50, Train MAE: 674433.7344, Valid MAE: 713490.8125
Epoch 28/50, Train MAE: 670015.5938, Valid MAE: 713480.8125
Epoch 29/50, Train MAE: 663659.7500, Valid MAE: 713470.3125
Epoch 30/50, Train MAE: 665968.9062, Valid MAE: 713459.3750
Epoch 31/50, Train MAE: 667789.0938, Valid MAE: 713447.9375
Epoch 32/50, Train MAE: 658714.9219, Valid MAE: 713436.0625
Epoch 33/50, Train MAE: 666920.0469, Valid MAE: 713423.6250
Epoch 34/50, Train MAE: 662265.8906, Valid MAE: 713410.6875
Epoch 35/50, Train MAE: 665102.3281, Valid MAE: 713397.2500
Epoch 36/50, Train MAE: 635776.7188, Valid MAE: 713383.1875
Epoch 37/50, Train MAE: 674706.9375, Valid MAE: 713368.6875
Epoch 38/50, Train MAE: 664550.5625, Valid MAE: 713353.6875
Epoch 39/50, Train MAE: 679749.5469, Valid MAE: 713338.0625
Epoch 40/50, Train MAE: 673519.4219, Valid MAE: 713321.8750
Epoch 41/50, Train MAE: 650104.5312, Valid MAE: 713305.2500
Epoch 42/50, Train MAE: 645330.7500, Valid MAE: 713287.9375
Epoch 43/50, Train MAE: 631264.1172, Valid MAE: 713270.1250
Epoch 44/50, Train MAE: 658698.1250, Valid MAE: 713251.6875
Epoch 45/50, Train MAE: 665561.8906, Valid MAE: 713232.6250
Epoch 46/50, Train MAE: 651798.2812, Valid MAE: 713213.0000
Epoch 47/50, Train MAE: 654373.3281, Valid MAE: 713192.7500
Epoch 48/50, Train MAE: 711001.4062, Valid MAE: 713171.9375
Epoch 49/50, Train MAE: 622832.2656, Valid MAE: 713150.5000
Epoch 50/50, Train MAE: 656350.6406, Valid MAE: 713128.4375

[INFO 06-19 19:55:20] ax.service.managed_loop: Running optimization trial 11...

Test MAE: 648506.3750

/home/matteo/Documents/GNN-test2/SEPH_MODELS/env3/lib/python3.10/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

Epoch 1/50, Train MAE: 663309.4375, Valid MAE: 713625.3125
Epoch 2/50, Train MAE: 663308.0625, Valid MAE: 713623.8750
Epoch 3/50, Train MAE: 663306.6250, Valid MAE: 713622.3750
Epoch 4/50, Train MAE: 663305.2500, Valid MAE: 713620.9375
Epoch 5/50, Train MAE: 663303.7500, Valid MAE: 713619.5625
Epoch 6/50, Train MAE: 663302.3125, Valid MAE: 713618.0625
Epoch 7/50, Train MAE: 663300.9375, Valid MAE: 713616.7500
Epoch 8/50, Train MAE: 663299.4375, Valid MAE: 713615.2500
Epoch 9/50, Train MAE: 663298.0625, Valid MAE: 713613.8125
Epoch 10/50, Train MAE: 663296.6250, Valid MAE: 713612.4375
Epoch 11/50, Train MAE: 663295.1250, Valid MAE: 713610.8750
Epoch 12/50, Train MAE: 663293.6250, Valid MAE: 713609.3125
Epoch 13/50, Train MAE: 663292.0625, Valid MAE: 713607.8750
Epoch 14/50, Train MAE: 663290.6250, Valid MAE: 713606.2500
Epoch 15/50, Train MAE: 663289.0000, Valid MAE: 713604.7500
Epoch 16/50, Train MAE: 663287.4375, Valid MAE: 713603.1250
Epoch 17/50, Train MAE: 663285.7500, Valid MAE: 713601.4375
Epoch 18/50, Train MAE: 663284.1250, Valid MAE: 713599.7500
Epoch 19/50, Train MAE: 663282.5625, Valid MAE: 713598.0000
Epoch 20/50, Train MAE: 663280.7500, Valid MAE: 713596.2500
Epoch 21/50, Train MAE: 663279.0000, Valid MAE: 713594.5000
Epoch 22/50, Train MAE: 663277.1250, Valid MAE: 713592.6250
Epoch 23/50, Train MAE: 663275.3125, Valid MAE: 713590.6875
Epoch 24/50, Train MAE: 663273.4375, Valid MAE: 713588.8125
Epoch 25/50, Train MAE: 663271.4375, Valid MAE: 713586.8125
Epoch 26/50, Train MAE: 663269.5625, Valid MAE: 713584.6875
Epoch 27/50, Train MAE: 663267.4375, Valid MAE: 713582.6250
Epoch 28/50, Train MAE: 663265.3750, Valid MAE: 713580.5000
Epoch 29/50, Train MAE: 663263.1250, Valid MAE: 713578.3125
Epoch 30/50, Train MAE: 663261.0000, Valid MAE: 713576.0000
Epoch 31/50, Train MAE: 663258.6875, Valid MAE: 713573.6250
Epoch 32/50, Train MAE: 663256.3750, Valid MAE: 713571.1875
Epoch 33/50, Train MAE: 663254.0000, Valid MAE: 713568.7500
Epoch 34/50, Train MAE: 663251.4375, Valid MAE: 713566.2500
Epoch 35/50, Train MAE: 663248.9375, Valid MAE: 713563.5625
Epoch 36/50, Train MAE: 663246.3125, Valid MAE: 713561.0000
Epoch 37/50, Train MAE: 663243.6250, Valid MAE: 713558.1875
Epoch 38/50, Train MAE: 663240.8750, Valid MAE: 713555.3750
Epoch 39/50, Train MAE: 663238.0000, Valid MAE: 713552.4375
Epoch 40/50, Train MAE: 663235.0625, Valid MAE: 713549.4375
Epoch 41/50, Train MAE: 663232.0625, Valid MAE: 713546.3750
Epoch 42/50, Train MAE: 663229.0000, Valid MAE: 713543.1875
Epoch 43/50, Train MAE: 663225.7500, Valid MAE: 713539.8750
Epoch 44/50, Train MAE: 663222.5625, Valid MAE: 713536.5625
Epoch 45/50, Train MAE: 663219.2500, Valid MAE: 713533.0000
Epoch 46/50, Train MAE: 663215.6875, Valid MAE: 713529.4375
Epoch 47/50, Train MAE: 663212.1250, Valid MAE: 713525.8750
Epoch 48/50, Train MAE: 663208.6250, Valid MAE: 713522.1875
Epoch 49/50, Train MAE: 663204.8750, Valid MAE: 713518.3125
Epoch 50/50, Train MAE: 663201.0000, Valid MAE: 713514.4375

[INFO 06-19 19:57:29] ax.service.managed_loop: Running optimization trial 12...

Test MAE: 648891.8125
Epoch 1/50, Train MAE: 663309.8750, Valid MAE: 712176.4375
Epoch 2/50, Train MAE: 661853.0625, Valid MAE: 707391.3750
Epoch 3/50, Train MAE: 657048.4375, Valid MAE: 695890.6875
Epoch 4/50, Train MAE: 645581.8750, Valid MAE: 673968.1250
Epoch 5/50, Train MAE: 623938.3125, Valid MAE: 637246.8750
Epoch 6/50, Train MAE: 588218.1250, Valid MAE: 582937.5625
Epoch 7/50, Train MAE: 535369.0000, Valid MAE: 507411.4375
Epoch 8/50, Train MAE: 463757.7812, Valid MAE: 432798.2812
Epoch 9/50, Train MAE: 385373.7812, Valid MAE: 400639.9375
Epoch 10/50, Train MAE: 356259.9688, Valid MAE: 422545.5000
Epoch 11/50, Train MAE: 399558.6250, Valid MAE: 451083.5000
Epoch 12/50, Train MAE: 436759.5625, Valid MAE: 448834.7500
Epoch 13/50, Train MAE: 434045.8125, Valid MAE: 427074.0938
Epoch 14/50, Train MAE: 406093.5625, Valid MAE: 403095.8125
Early stopping

[INFO 06-19 19:58:08] ax.service.managed_loop: Running optimization trial 13...

Test MAE: 337982.8750
Epoch 1/50, Train MAE: 673955.5938, Valid MAE: 711859.6875
Epoch 2/50, Train MAE: 667997.0000, Valid MAE: 704404.2500
Epoch 3/50, Train MAE: 640990.5938, Valid MAE: 685544.3750
Epoch 4/50, Train MAE: 625908.4688, Valid MAE: 647858.8125
Epoch 5/50, Train MAE: 581245.5938, Valid MAE: 584410.8125
Epoch 6/50, Train MAE: 534103.2031, Valid MAE: 489731.1562
Epoch 7/50, Train MAE: 418369.5625, Valid MAE: 415210.7500
Epoch 8/50, Train MAE: 368535.2656, Valid MAE: 405060.0000
Epoch 9/50, Train MAE: 392001.9844, Valid MAE: 435828.6875
Epoch 10/50, Train MAE: 409818.5781, Valid MAE: 427108.8438
Epoch 11/50, Train MAE: 397751.0781, Valid MAE: 401680.7500
Epoch 12/50, Train MAE: 361105.5781, Valid MAE: 399937.3438
Epoch 13/50, Train MAE: 349895.3750, Valid MAE: 413620.5000
Epoch 14/50, Train MAE: 367951.0156, Valid MAE: 422709.7812
Epoch 15/50, Train MAE: 387730.3750, Valid MAE: 420984.5625
Epoch 16/50, Train MAE: 361776.3750, Valid MAE: 411082.2812
Epoch 17/50, Train MAE: 347538.1875, Valid MAE: 399856.1562
Epoch 18/50, Train MAE: 357851.5469, Valid MAE: 393083.5312
Epoch 19/50, Train MAE: 347661.8594, Valid MAE: 392926.5000
Epoch 20/50, Train MAE: 369542.6719, Valid MAE: 392126.2812
Epoch 21/50, Train MAE: 346917.0000, Valid MAE: 391648.3125
Epoch 22/50, Train MAE: 351410.4062, Valid MAE: 395147.5938
Epoch 23/50, Train MAE: 344221.9219, Valid MAE: 399159.9375
Epoch 24/50, Train MAE: 352413.9688, Valid MAE: 401255.9375
Epoch 25/50, Train MAE: 358738.2969, Valid MAE: 399228.1875
Epoch 26/50, Train MAE: 343840.8281, Valid MAE: 395067.4375
Early stopping

[INFO 06-19 19:59:16] ax.service.managed_loop: Running optimization trial 14...

Test MAE: 336756.3750
Epoch 1/50, Train MAE: 663310.0000, Valid MAE: 709293.6875
Epoch 2/50, Train MAE: 658984.4375, Valid MAE: 695991.3750
Epoch 3/50, Train MAE: 645775.0625, Valid MAE: 666880.0000
Epoch 4/50, Train MAE: 617159.7500, Valid MAE: 614975.2500
Epoch 5/50, Train MAE: 566916.2500, Valid MAE: 536383.5625
Epoch 6/50, Train MAE: 491249.6562, Valid MAE: 441456.8125
Epoch 7/50, Train MAE: 396941.7812, Valid MAE: 399874.2500
Epoch 8/50, Train MAE: 356881.6250, Valid MAE: 432776.1250
Epoch 9/50, Train MAE: 414103.8125, Valid MAE: 459022.6562
Epoch 10/50, Train MAE: 446855.6562, Valid MAE: 445577.7812
Epoch 11/50, Train MAE: 430421.3438, Valid MAE: 415491.9688
Epoch 12/50, Train MAE: 390953.3750, Valid MAE: 396341.8438
Epoch 13/50, Train MAE: 359826.2188, Valid MAE: 404676.3438
Epoch 14/50, Train MAE: 354618.1875, Valid MAE: 420248.8438
Epoch 15/50, Train MAE: 370724.2188, Valid MAE: 432081.0000
Epoch 16/50, Train MAE: 385928.9375, Valid MAE: 434730.2812
Epoch 17/50, Train MAE: 389555.3750, Valid MAE: 427713.0000
Early stopping

[INFO 06-19 20:00:04] ax.service.managed_loop: Running optimization trial 15...

Test MAE: 341731.7812
Epoch 1/50, Train MAE: 701098.2344, Valid MAE: 712053.3125
Epoch 2/50, Train MAE: 658408.2656, Valid MAE: 702343.1875
Epoch 3/50, Train MAE: 632622.8125, Valid MAE: 672635.5625
Epoch 4/50, Train MAE: 611287.8047, Valid MAE: 605839.3750
Epoch 5/50, Train MAE: 512686.5312, Valid MAE: 487162.7188
Epoch 6/50, Train MAE: 419710.8906, Valid MAE: 404042.4688
Epoch 7/50, Train MAE: 372942.2031, Valid MAE: 422084.5625
Epoch 8/50, Train MAE: 383114.4922, Valid MAE: 413065.9062
Epoch 9/50, Train MAE: 360323.2656, Valid MAE: 399318.4688
Epoch 10/50, Train MAE: 354842.8594, Valid MAE: 416948.0625
Epoch 11/50, Train MAE: 368147.9375, Valid MAE: 419690.2188
Epoch 12/50, Train MAE: 361607.8281, Valid MAE: 406207.2500
Epoch 13/50, Train MAE: 341326.8906, Valid MAE: 394898.9375
Epoch 14/50, Train MAE: 349211.4453, Valid MAE: 393910.0938
Epoch 15/50, Train MAE: 362669.6172, Valid MAE: 392720.4062
Epoch 16/50, Train MAE: 350131.6406, Valid MAE: 394157.5312
Epoch 17/50, Train MAE: 335900.3984, Valid MAE: 396605.0312
Epoch 18/50, Train MAE: 337253.6953, Valid MAE: 395152.2812
Epoch 19/50, Train MAE: 324676.3750, Valid MAE: 391486.9688
Epoch 20/50, Train MAE: 343975.4453, Valid MAE: 390115.6562
Epoch 21/50, Train MAE: 343996.2812, Valid MAE: 388519.3750
Epoch 22/50, Train MAE: 315061.3594, Valid MAE: 386845.4062
Epoch 23/50, Train MAE: 395214.5469, Valid MAE: 384984.5625
Epoch 24/50, Train MAE: 347949.0781, Valid MAE: 384103.0938
Epoch 25/50, Train MAE: 322492.2734, Valid MAE: 382099.8438
Epoch 26/50, Train MAE: 310098.7305, Valid MAE: 381356.1562
Epoch 27/50, Train MAE: 296665.6914, Valid MAE: 382759.0625
Epoch 28/50, Train MAE: 294217.1133, Valid MAE: 382849.0938
Epoch 29/50, Train MAE: 302524.4688, Valid MAE: 383485.3438
Epoch 30/50, Train MAE: 302356.3672, Valid MAE: 384681.5312
Epoch 31/50, Train MAE: 314192.0781, Valid MAE: 385713.6875
Early stopping
Test MAE: 332705.7812
Best parameters: {'lr': 0.03130484111561095, 'batch_size': 128, 'aggregation': 'mean', 'hid': 128, 'layers': 2}
Means {'remaining_time_mae': 328376.7541323189}
Experiment: Experiment(None)

In [29]:
from ax.service.utils.report_utils import exp_to_df

results = exp_to_df(experiment)

[WARNING 06-19 20:01:50] ax.service.utils.report_utils: Column reason missing for all trials. Not appending column.

In [30]:
results.sort_values(by="remaining_time_mae")

,trial_index,arm_name,trial_status,generation_method,remaining_time_mae,lr,batch_size,aggregation,hid,layers
7,7,7_0,COMPLETED,BO_MIXED,328314.28125,0.100000,128,max,128,2
1,1,1_0,COMPLETED,Sobol,330127.90625,0.042125,128,sum,128,2
8,8,8_0,COMPLETED,BO_MIXED,330205.00000,0.100000,128,mean,128,2
14,14,14_0,COMPLETED,BO_MIXED,332705.78125,0.031305,128,mean,128,2
12,12,12_0,COMPLETED,BO_MIXED,336756.37500,0.014951,256,sum,128,2
11,11,11_0,COMPLETED,BO_MIXED,337982.87500,0.027176,512,sum,128,2
5,5,5_0,COMPLETED,Sobol,338728.71875,0.013215,128,mean,128,2
13,13,13_0,COMPLETED,BO_MIXED,341731.78125,0.100000,512,max,128,2
6,6,6_0,COMPLETED,BO_MIXED,344461.90625,0.005030,128,sum,128,2
4,4,4_0,COMPLETED,Sobol,370438.81250,0.002844,512,sum,128,2
2,2,2_0,COMPLETED,Sobol,634240.50000,0.003498,512,mean,128,2
3,3,3_0,COMPLETED,Sobol,641460.81250,0.000763,256,max,128,2
9,9,9_0,COMPLETED,BO_MIXED,648506.37500,0.000100,128,max,128,2
10,10,10_0,COMPLETED,BO_MIXED,648891.81250,0.000100,512,sum,128,2
0,0,0_0,COMPLETED,Sobol,648929.62500,0.000187,256,mean,128,2

In [31]:
results = results.sort_values(by="remaining_time_mae")

In [32]:
results.to_csv(f"results/{dataset}.csv", sep=",")